### ISSUE TITLE
Remove `smo-database` sub-module and move plug-in code for writers

### ISSUE THREAD

**Issue by pekasen** [Leibniz-HBI/dabapush#33]
The `smo-database` sub-module hinders testing in GitHub Actions (see error log in #32 ) and makes installation a nightmare (and to be frank impossible for people outside of our org).

Thus, as `dabapush`itself does not dependent on code from `smo-database`we should remove the depedency, move  the database plugins to `smo-database` for good, let them register themselves against `dabapush` through the entry point and ship `smo-database` as another package via Pypi.

**Comment by pekasen** [comment]
Ping @adyk007 for heads up in #27, may be you can pull the above in that issue as well?

**Comment by adyk007** [comment]
Alright this sounds good and would actually reduce the headache of initialising everything in dabapush.

**Comment by pekasen** [comment]
Closed with #42.
